### ISSUE TITLE
модуль смены каналов

### ISSUE THREAD

**Issue by apostol-roman** [tera-proxy/tera-proxy#5]
добрый день. подскажи пожалуйста по модулю для быстрого переключения каналов, я пытаюсь его создать но он не хочет работать ( что я делаю не так? помоги пожалуйста [https://github.com/apostol-roman/swich-channels-instantly](url)

**Comment by pinkipi** [comment]
It's not possible. The channel switch timer is server-sided.

Это невозможно. Таймер переключения каналов находится на стороне сервера.
